# Generated by Django 4.2.11 on 2024-05-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile',
            field=models.CharField(max_length=20, unique=True, verbose_name='qq邮箱'),
        ),
    ]
