# Generated by Django 4.2.11 on 2024-05-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_active',
            field=models.BooleanField(default=False, verbose_name='邮箱验证状态'),
        ),
    ]
