# Generated by Django 4.2.11 on 2024-05-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address_users_default_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='手机'),
        ),
    ]
